=== HashKernel/DAM/Lenguajes de marcas/XML/EjercicioFinal/empresa.dtd
<!ELEMENT empresa (pedido+)>
<!ELEMENT pedido (sucursal,direccion+,trabajador,fechapedido,observacion,plazorevision,articulo+)>
<!ELEMENT sucursal (#PCDATA)>
<!ATTLIST sucursal codigo CDATA #REQUIRED>

<!ELEMENT direccion (#PCDATA)>
<!ELEMENT trabajador (#PCDATA)>
<!ELEMENT fechapedido (#PCDATA)>
<!ELEMENT observacion (#PCDATA)>
<!ELEMENT plazorevision (#PCDATA)>

<!ELEMENT articulo (unidades,precio,observaciones)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ATTLIST articulo codigo CDATA #REQUIRED>

=== HashKernel/DAM/Lenguajes de marcas/XML/EjercicioFinal/empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "empresa.dtd">

<empresa>
  <pedido>
    <sucursal codigo="A1234567">Innova</sucursal>
    <direccion>Calle Nueva</direccion>
    <direccion>Calle Ollerias</direccion>
    <trabajador>Luca</trabajador>
    <fechapedido>19-02-2023</fechapedido>
    <observacion>urgente</observacion>
    <plazorevision>4</plazorevision>
    <articulo codigo="ABC-123">
      <unidades>3</unidades>
      <precio>10.3</precio>
      <observaciones>reacondicionado</observaciones>
    </articulo>
    <articulo codigo="DEF-456">
      <unidades>8</unidades>
      <precio>39.99</precio>
      <observaciones>Ninguna</observaciones>
     </articulo>
  </pedido>
</empresa>
