=== HashKernel/DAM/Lenguajes de marcas/XML/DTD/listacursos.dtd
<!ELEMENT listacursos (curso+)>
<!ELEMENT curso (alumno+)>
<!ELEMENT alumno (DNI,nombre,apellido,segundo_apellido?,lista_asignaturas)>

<!ELEMENT DNI (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT segundo_apellido (#PCDATA)>

<!ELEMENT lista_asignaturas (asignatura+)>
<!ELEMENT asignatura (nombre,profesor)>
<!ATTLIST asignatura codigo CDATA #REQUIRED>

<!ELEMENT profesor (NRP,nombre,apellido,segundo_apellido?)>
<!ELEMENT NRP (#PCDATA)>

=== HashKernel/DAM/Lenguajes de marcas/XML/DTD/listacursos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacursos SYSTEM "listacursos.dtd">

<listacursos>
  <curso>
    <alumno>
      <DNI>44e</DNI>
      <nombre>Juan</nombre>
      <apellido>Sancapellido</apellido>
      <lista_asignaturas>
        <asignatura codigo="LM1">
        <nombre>Leng marcas</nombre>
        <profesor>
          <NRP>8</NRP>
          <nombre>Manuel</nombre>
          <apellido>PÃ©rez</apellido>
        </profesor>
        </asignatura>
      </lista_asignaturas>
    </alumno>
  </curso>
</listacursos>
